# SPDX-FileCopyrightText: 2023 Risk.Ident GmbH <contact@riskident.com>
#
# SPDX-License-Identifier: CC0-1.0

extends: ../.markdownlint.yaml

# MD013/line-length - Line length
# New-lines in GitHub issues and PRs turn into <br/>,
# so line length limit is more intrusive
MD013: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false
