name: markdownlint

on:
  pull_request:
    paths:
      - '**.md'
      - '.github/workflows/markdownlint.yml'

jobs:
  markdownlint:
    uses: platform/reusable-workflows/.github/workflows/markdownlint.yml@main
